export enum HeaderRoutesList {
  HOME = '/',
  LOGIN = 'login',
  SIGNIN = 'signin',
  RESET_PSWRD = 'reset',
  MASTER_CATALOG = 'master_catalog',
  STUDIO_CATALOG = 'salon_catalog',
  BLOG = 'blog',
  PARTNERS = 'partners',
  SIGNIN_SUCCESS = 'success',
  PROFILE = 'profile/:id',
  CONTACTS = 'contacts',
  ERROR = 'error_page',
  BLOG_POST = '/post/:id',
  NEW_PASSWORD = '/reset_password_confirm/:uid/:token',
}
